name: Build & Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  Build-Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci && npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - id: deployment
        uses: actions/deploy-pages@v1
