name: Close PR Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  Close:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Remove Preview folder
        run: rm -r ./pr/${{ github.event.pull_request.number }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
